SAS-76, SAS-66, SAS-51 # fixed dekel errors
corona-code-monkeys/soccer-association-system pull request #82
Opened 2020-04-24 15:33 UTC by MrBahur

2020-04-24 16:45 UTC, AmitNachimovitz reviewed
I think u must add to your classes names "UT, IT, and AT" accordingly. Otherwise, I'm not sure our automation will recognize it.

2020-04-24 16:54 UTC, AmitNachimovitz requested changes
For the changes I mentioned earlier.

2020-04-24 17:03 UTC, Chen2908 commented on src/main/java/com/SAS/crudoperations/CRUD.java
> +    public static boolean addRefereesToLeagueInSeason(League league, Season season, List<Referee> referees) {
I would prefer my real name be left out..

2020-04-24 17:03 UTC, Chen2908 commented on src/test/java/com/SAS/LeagueManagement/assignRefereesToLeagueInSpecificSeasonBottomUp.java
> +        Assertions.assertTrue(isLeagueExistStub(league));
Whats the difference between this and assertTrue(.....)?
We used assertTrue and imported import static org.junit.Assert.*;

2020-04-24 17:03 UTC, Chen2908 commented on src/test/java/com/SAS/LeagueManagement/initLeagueBottomUp.java
> +        Assertions.assertTrue(isLeagueExistStub(league));
Same here (and in other places)

2020-04-25 10:20 UTC, yaarm approved these changes

2020-04-25 10:21 UTC, AmitNachimovitz approved these changes

2020-04-25 10:21 UTC, merged