Sas 82 league init at
corona-code-monkeys/soccer-association-system pull request #92
Opened 2020-04-25 21:21 UTC by dekellevy93

After finshing at for league init

2020-04-25 22:38 UTC, yaarm requested changes
I think it would be better if you would split the test for each acceptance tests separate:
as: 9.1 - one success test, one fail test.
9.2 - one success test, one fail test.
and so on.

2020-04-26 07:07 UTC, dekellevy93 commented
in the case of the failing tests, i agree. but in the success tests, each of them relies on the previous test, so it will be a lot of dup code...

2020-04-26 07:33 UTC, MrBahur commented
I agree with Yaar, id rather have duplicate code then 1 test that test to UC, because if it fail, i don't know where it failed, plus, you can use BeforeEach to save the duplicate code if you want to... not a must.

2020-04-26 07:57 UTC, dekellevy93 commented
changed as your request

2020-04-26 18:05 UTC, yaarm requested changes

2020-04-26 18:05 UTC, yaarm commented on src/test/java/com/SAS/acceptanceTests/LeagueManagementAT.java
> +        System.out.println("You have selected to edit association settings");
I don't understand which user is it - cause there is no privileges checking.

2020-04-26 18:05 UTC, yaarm commented on src/test/java/com/SAS/acceptanceTests/LeagueManagementAT.java
> +            System.out.println("The referee is already assigned for the league in this season");
I don't understand why this test fails, I think you need to define this referee for the season in the beginning of the test under setUp comment. If this is suppose to be a referee that already exists - I would expect the function of add referee to season would return false - and than check it with asserFalse().

2020-04-26 18:05 UTC, yaarm commented on src/test/java/com/SAS/acceptanceTests/LeagueManagementAT.java
> +        Assertions.assertFalse(CRUD.isLeagueExist(new League("Liga Leumit")));
I think you need to add the function of "addSeasonToLeague" in the LeagueManagement controller and than it would return false.

2020-04-26 18:05 UTC, yaarm commented on src/test/java/com/SAS/acceptanceTests/LeagueManagementAT.java
> +        if (CRUD.addLeague(league)) {
I think you should call the function in the controller instead of the CRUD.

2020-04-27 21:09 UTC, AmitNachimovitz approved these changes

2020-04-27 21:10 UTC, merged